/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OdemeSonucRouteImport } from './routes/odeme.sonuc'
import { Route as ApiIyzicoCheckoutRouteImport } from './routes/api/iyzico-checkout'
import { Route as ApiPublicIncrementDesignOrdersRouteImport } from './routes/api/public/increment-design-orders'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OdemeSonucRoute = OdemeSonucRouteImport.update({
  id: '/odeme/sonuc',
  path: '/odeme/sonuc',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIyzicoCheckoutRoute = ApiIyzicoCheckoutRouteImport.update({
  id: '/api/iyzico-checkout',
  path: '/api/iyzico-checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIncrementDesignOrdersRoute =
  ApiPublicIncrementDesignOrdersRouteImport.update({
    id: '/api/public/increment-design-orders',
    path: '/api/public/increment-design-orders',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/iyzico-checkout': typeof ApiIyzicoCheckoutRoute
  '/odeme/sonuc': typeof OdemeSonucRoute
  '/api/public/increment-design-orders': typeof ApiPublicIncrementDesignOrdersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/iyzico-checkout': typeof ApiIyzicoCheckoutRoute
  '/odeme/sonuc': typeof OdemeSonucRoute
  '/api/public/increment-design-orders': typeof ApiPublicIncrementDesignOrdersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/iyzico-checkout': typeof ApiIyzicoCheckoutRoute
  '/odeme/sonuc': typeof OdemeSonucRoute
  '/api/public/increment-design-orders': typeof ApiPublicIncrementDesignOrdersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/api/iyzico-checkout'
    | '/odeme/sonuc'
    | '/api/public/increment-design-orders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/api/iyzico-checkout'
    | '/odeme/sonuc'
    | '/api/public/increment-design-orders'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/api/iyzico-checkout'
    | '/odeme/sonuc'
    | '/api/public/increment-design-orders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ApiIyzicoCheckoutRoute: typeof ApiIyzicoCheckoutRoute
  OdemeSonucRoute: typeof OdemeSonucRoute
  ApiPublicIncrementDesignOrdersRoute: typeof ApiPublicIncrementDesignOrdersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/odeme/sonuc': {
      id: '/odeme/sonuc'
      path: '/odeme/sonuc'
      fullPath: '/odeme/sonuc'
      preLoaderRoute: typeof OdemeSonucRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/iyzico-checkout': {
      id: '/api/iyzico-checkout'
      path: '/api/iyzico-checkout'
      fullPath: '/api/iyzico-checkout'
      preLoaderRoute: typeof ApiIyzicoCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/increment-design-orders': {
      id: '/api/public/increment-design-orders'
      path: '/api/public/increment-design-orders'
      fullPath: '/api/public/increment-design-orders'
      preLoaderRoute: typeof ApiPublicIncrementDesignOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ApiIyzicoCheckoutRoute: ApiIyzicoCheckoutRoute,
  OdemeSonucRoute: OdemeSonucRoute,
  ApiPublicIncrementDesignOrdersRoute: ApiPublicIncrementDesignOrdersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
